version: "3.9"
services:
  crm:
    build: .
    container_name: crm_local
    ports:
      - "8080:80"
    # O arquivo .env deve ser criado localmente se houver vari√°veis de ambiente.
    # env_file:
    #   - .env
    restart: unless-stopped
